name: contrastive-learning
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - cudatoolkit=11.1
  - pytorch-lightning
  - matplotlib
  - click